# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
- name: WhitespaceTokenizer
- name: "CountVectorsFeaturizer"
  strip_accents: ascii
  lowercase: true
  stop_words:  [ "orange","ca","de","la", "le", "les", "leur", "leurs", "lui", "la", "m", "ma", "maintenant", "me", "mes", "moi", "mon", "nos", "notre", "sa", "ses", "ta", "te","tes", "ton", "trop", "tres", "un", "une", "des", "vos", "votre", "vous", "de", "à", "avec", "depuis","sur","tellement","que","quand","en","lorsque"]
- name: "CountVectorsFeaturizer"
  strip_accents: "ascii"
  lowercase: true
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "EmbeddingIntentClassifier"
  epochs: 300
  random_seed: 1
- name: "CRFEntityExtractor"
  features: 
    - ["low", "title", "upper"]
    - ["low", "bias", "prefix5", "prefix2", "suffix5", "suffix3", "suffix2", "upper", "title", "digit", "pattern"]
    - ["low", "title", "upper"]
- name: "EntitySynonymMapper"


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
